# Generated by Django 5.0 on 2024-01-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertype', '0003_addjob_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cv',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
