# Generated by Django 5.0 on 2024-01-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_phone_number_company_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Jobdetail',
        ),
    ]
