# Generated by Django 5.0 on 2024-01-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='line_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
