# Generated by Django 5.0 on 2024-01-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_alter_professor_options_alter_professor_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='username',
            field=models.CharField(default='adminupse', max_length=128, unique=True),
        ),
    ]
