# Generated by Django 5.0 on 2024-01-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('student_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('line_id', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('intern_job', models.CharField(max_length=200)),
                ('intern_des', models.CharField(max_length=200)),
                ('intern_company', models.CharField(max_length=200)),
                ('interest_job', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('gpa', models.CharField(max_length=10)),
                ('intern_start', models.DateField()),
                ('intern_end', models.DateField()),
                ('eng_skill', models.CharField(max_length=200)),
            ],
        ),
    ]
