# Generated by Django 5.0 on 2024-01-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_line',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
