# Generated by Django 5.0 on 2024-01-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_id_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
