# Generated by Django 5.0 on 2024-01-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_role',
            field=models.CharField(blank=True, default='student', max_length=255),
        ),
    ]
